### PR TITLE
Removal of app/ and lib/Cake/Console/Templates/skel

### PR DESCRIPTION
**Pull request by RGGN**
Those two directories contain example code that is redefining some classes in the root namespace, if we try to autoload them we find conflicts. Since this is not production code, and it is just an example, I think we can remove it completely, so we don't have 'AppController' defined many times.

### CODE REVIEW

**Comment by beinbm** [comment]
Could we just exclude them from Classmap instead?
https://getcomposer.org/doc/04-schema.md#exclude-files-from-classmaps

**Comment by beinbm** [comment]
and test fail

**Comment by beinbm** [comment]
see https://github.com/fotografde/cakephp2/pull/6 

does that help you too?

**Comment by RGGN** [comment]
Will exclude them from classmap instead, I missed this. Thanks for checking

**Pull request closed without merging**
